translate_o_rama/accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"
urlpatterns = [
    path('custom_login/', views.custom_login, name="custom_login"),
    path('register/', views.register, name="register"),
    path('user_profile/', views.user_profile, name="user_profile"),
    path('change_email/', views.change_email, name="change_email"),
    path('change_password/', views.change_password, name="change_password"),
    path('user_dashboard/<int:user_id>', views.user_dashboard, name="user_dashboard"),
    path('send_message/<int:user_id>/<int:target_user_id>', views.send_message, name="send_message")
]

translate_o_rama/app/urls.py
from django.urls import path, include
from . import views

app_name = "app"
urlpatterns = [
    path('post/', views.post,  name="post"),
    path('job_listing/', views.job_listing, name="job_listing"),
    path('job_listing/<int:job_id>', views.job_bidding, name="job_bidding"),
    path('job_accept/<int:job_id>/<int:biddingOffer_id>', views.job_accept, name="job_accept"),
    path('complete_job/<int:job_id>', views.complete_job, name="complete_job"),
    path('rate_job/<int:job_id>', views.rate_job, name="rate_job"),
    path('dispute_job/<int:job_id>', views.dispute_job, name="dispute_job"),
]

translate_o_rama/translate_o_rama/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('jobs/', include('app.urls')),
    path('',  views.home,  name="home"),
]

translate_o_rama/app/models.py
from django.db import models
from decimal import Decimal
from django.core.validators import MinValueValidator, MaxValueValidator
from accounts.models import User

# Create your models here.


FIELD_CHOICES = (
    ("STATE_ART", "Art"),
    ("STATE_BUSINESS", "Business"),
    ("STATE_COMPUTERS", "Computers"),
    ("STATE_EDUCATION", "Education"),
    ("STATE_ENGINEERING", "Engineering"),
    ("STATE_FINANCE", "Finance"),
    ("STATE_LAW", "Law"),
    ("STATE_LITERATURE", "Literature"),
    ("STATE_MEDICINE", "Medicine"),
    ("STATE_SCIENCE", "Science"),
    ("STATE_SOCIAL", "Social Sciences"),
    ("STATE_TECHNOLOGY", "Technology"),
)

STATUS_CHOICES = (
    ("STATE_NOT_ASSIGNED", "Not assigned"),
    ("STATE_IN_PROGRESS", "In Progress"),
    ("STATE_COMPLETED", "Completed"),
)

STATUS_DISPUTE = (
    ("STATE_OPEN", "Open"),
    ("STATE_CLOSED", "Closed"),
)

class Job(models.Model):
    user = models.ForeignKey(User, related_name='user', on_delete=models.CASCADE)
    title = models.CharField(unique=True, max_length=120)
    description = models.TextField(blank=True)
    source_language = models.CharField(max_length=20)
    target_language = models.CharField(max_length=20)
    field = models.CharField(choices=FIELD_CHOICES, max_length=20)
    budget = models.DecimalField(decimal_places=2, max_digits=10, validators=[MinValueValidator(Decimal('0.01'))])
    source_text = models.TextField()
    translated_text = models.TextField(blank=True)
    status = models.CharField(choices=STATUS_CHOICES, default=STATUS_CHOICES[0][0], max_length=20)
    translator = models.ForeignKey(User, null = True, blank = True, related_name='translator', on_delete=models.DO_NOTHING, limit_choices_to={'is_translator': True})

    def __str__(self):
        return f"{self.title}"


class BiddingOffer(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    translator = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'is_translator': True})
    quote = models.DecimalField(decimal_places=2, max_digits=10, validators=[MinValueValidator(Decimal('0.01'))])

    def __str__(self):
        return f"{self.job} - {self.translator}"
    
class Rating(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    rating = models.IntegerField(default=3, validators=[MinValueValidator(1), MaxValueValidator(5)])

    def __str__(self):
        return f"{self.job.title} - {self.rating}"
    
class Dispute(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    status = models.CharField(choices=STATUS_DISPUTE, default=STATUS_DISPUTE[0][0], max_length=20)
    reason = models.TextField()

    def __str__(self):
        return f"{self.job.title} - By: {self.job.user} - On: {self.job.translator}"

translate_o_rama/app/templates/app/base.html
{% load static %}
<html>
  <head>
    <title>Translate-O-Rama</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js" integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'app/css/app.css' %}">
  </head>
  <body>    
    <div class="page-header">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Translate-O-Rama</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/jobs/job_listing">Jobs <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'app:post' %}">Post a Job</a>
            </li>
          </ul>

          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}              
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'accounts:user_dashboard' user.id %}"> {{user.username}}'s Dashboard</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'accounts:user_profile' %}"> {{user.username}}'s Profile</a>
              </li>
              {% if user.is_superuser %}
                <li class="nav-item active">
                  <a class="nav-link" href="/admin"> Admin</a>
                </li>
              {% endif %}
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'logout' %}"> Log Out</a>
              </li>
            {% else %}
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'accounts:custom_login' %}">Log In</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>
    
    <div class="content container">
      <div class="row">
        <div class="col-md-12">
          <div class="jumbotron fluid-jumbotron">
            <div class="container">
              <h1 class="display-4">Translate-O-Rama</h1>
              <p class="lead">Your one stop place for all your translations!</p>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

translate_o_rama/app/templates/app/complete_job.html
{% extends 'app/base.html' %}
{% block content %}
{% load widget_tweaks %}
 
<div class="card mb-3 border-primary p-3">
    <h2 class="text-center bg-primary text-white rounded pt-2 pb-2 mb-4">Translate job</h2>

    <div class="container overflow-hidden">
        <div class="row">

            <div class="col-6">
                <div class="card border-primary mb-3">
                    <div class="card-header text-primary">Job info - {{ job.title }}</div>
                    <div class="card-body text-primary">
                        <h2 class="card-title">From {{ job.source_language }} to {{ job.target_language }}</h2>
                        <h5 class="card-title">Description: {{ job.description }}</h5>
                        <p>Source text: {{ job.source_text }}</p>
                    </div>
                </div>
                
            </div>

            <div class="col-6">
                <form method="post">
                    {% csrf_token %}

                    {% for hidden in form.hidden_fields %}
                      {{ hidden }}
                    {% endfor %}
                
                    {% for field in form.visible_fields %}
                      <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field|add_class:'form-control' }}
                        {% for error in field.errors %}
                          <div class="alert alert-danger">{{ error }}</div>
                        {% endfor %}
                      </div>
                    {% endfor %}
                
                    {% if form.non_field_errors %}
                      <div class="alert alert-danger">
                        {{ form.non_field_errors }}
                      </div>
                    {% endif %}
                
                    <div class="form-group">
                      <button type="submit" class="btn btn-primary">
                        <span class="glyphicon glyphicon-ok"></span> Post job
                      </button>
                    </div>
                
                                </form>            
            </div>
        </div>
    </div>
</div>



{% endblock %}

translate_o_rama/app/templates/app/dispute_job.html
{% extends 'app/base.html' %}
{% block content %}
{% load widget_tweaks %}
 
<div class="card mb-3 border-primary p-3">
    <h2 class="text-center bg-primary text-white rounded pt-2 pb-2 mb-4">Dispute a job</h2>

    <div class="container overflow-hidden">
        <div class="row">

            <div class="col-6">
                <div class="card border-primary mb-3">
                    <div class="card-header text-primary">Job info - {{ job.title }}</div>
                    <div class="card-body text-primary">
                        <h2 class="card-title">From {{ job.source_language }} to {{ job.target_language }}</h2>
                        <h5 class="card-title">Description: {{ job.description }}</h5>
                        <p>Source text: {{ job.source_text }}</p>
                        <p>Translated text: {{ job.translated_text }}</p>
                    </div>
                </div>
                
            </div>

            <div class="col-6">
                <form method="post">
                    {% csrf_token %}

                    {% for hidden in form.hidden_fields %}
                      {{ hidden }}
                    {% endfor %}
                
                    {% for field in form.visible_fields %}
                      <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field|add_class:'form-control' }}
                        {% for error in field.errors %}
                          <div class="alert alert-danger">{{ error }}</div>
                        {% endfor %}
                      </div>
                    {% endfor %}
                
                    {% if form.non_field_errors %}
                      <div class="alert alert-danger">
                        {{ form.non_field_errors }}
                      </div>
                    {% endif %}
                
                    <div class="form-group">
                      <button type="submit" class="btn btn-primary">
                        <span class="glyphicon glyphicon-ok"></span> Send dispute
                      </button>
                    </div>
                
                </form>            
            </div>
        </div>
    </div>
</div>

{% endblock %}

translate_o_rama/app/templates/app/home.html
{% extends 'app/base.html' %}
{% block content %}

<h1 class="display-4">Home</h1>

{% endblock %}

translate_o_rama/app/templates/app/job_bidding.html
{% extends 'app/base.html' %}
{% block content %}
{% load widget_tweaks %}
 
<div class="card mb-3 border-primary p-3">
    <h2 class="text-center bg-primary text-white rounded pt-2 pb-2 mb-4">Bid on a job</h2>

    <div class="container overflow-hidden">
        <div class="row">

            <div class="col-6">
                <div class="card border-primary mb-3">
                    <div class="card-header text-primary">Job info - {{ job.title }}</div>
                    <div class="card-body text-primary">
                        <h2 class="card-title">From {{ job.source_language }} to {{ job.target_language }}</h2>
                        <h1 class="card-title">Budget: {{ job.budget }}</h1>
                        <h4 class="card-title">Job field: {{ job.get_field_display }}</h4>
                        <h5 class="card-title">Description: {{ job.description }}</h5>
                        <p>Source text: {{ job.source_text }}</p>
                    </div>
                </div>
                
            </div>

            <div class="col-6">
                <div class="row">
                    <div class="col-4">
                        <h2 class="text-primary">By: <strong><a href="{% url 'accounts:user_dashboard' job.user.id %}">{{ job.user.username }}</a></strong></h2>
                    </div>
                    <div class="col-8">
                        {% if not job.user == user %}
                            <p><a class="btn btn-primary" href="{% url 'accounts:send_message' user.id job.user.id %}">Message User</a></p>
                        {% endif %}    
                    </div>
                </div>

                <h2 class="card-title text-primary">Your bid</h2>

                <form method="post">
                    {% csrf_token %}

                    {% for hidden in form.hidden_fields %}
                      {{ hidden }}
                    {% endfor %}
                
                    {% for field in form.visible_fields %}
                      <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field|add_class:'form-control' }}
                        {% for error in field.errors %}
                          <div class="alert alert-danger">{{ error }}</div>
                        {% endfor %}
                      </div>
                    {% endfor %}
                
                    {% if form.non_field_errors %}
                      <div class="alert alert-danger">
                        {{ form.non_field_errors }}
                      </div>
                    {% endif %}
                
                    <div class="form-group">
                      <button type="submit" class="btn btn-primary">
                        <span class="glyphicon glyphicon-ok"></span> Bid on job
                      </button>
                    </div>
                
                                </form>            
            </div>
        </div>
    </div>
</div>

{% endblock %}

translate_o_rama/app/templates/app/job_listing.html
{% extends 'app/base.html' %}
{% block content %}

{% if error_message %}
    <div class="alert-danger p-3 mb-3">{{ error_message }}</div>
{% endif %}

<div class="card mb-3 border-primary p-3">
    <h2 class="text-center bg-primary text-white rounded pt-2 pb-2 mb-4">All jobs</h2>

    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="list-group d-flex flex-wrap justify-content-around">
                    {% for job in jobs %}
                    <div>

                        <div class="container card bg-white text-primary rounded pt-2 pb-2 mx-2 border-primary" >
                            <div class="row text-center">
                                <h1 class="col-12">Title: {{ job.title }}</h5>
                            </div>

                            <div class="row text-center">
                                <h2 class="col-12">By: <strong><a href="{% url 'accounts:user_dashboard' job.user.id %}">{{ job.user.username }}</a></strong></h2>
                            </div>

                            <div class="row mb-1">
                                <h5 class="col-12">Description: {{ job.description }}</h5>
                            </div>

                            <div class="container card border-primary rounded">
                                <div class="row justify-content-around">
                                    <div class="col-4">
                                        <strong>SOURCE</strong> {{ job.source_language }}
                                        <span></span>
                                    </div>
                                    <div class="col-4">
                                        <strong>TARGET</strong> {{ job.target_language }}
                                    </div>
                                </div>

                                <div class="row justify-content-around">
                                    <div class="col-4">
                                        <strong>JOB FIELD</strong> {{ job.get_field_display }}
                                    </div>

                                    <div class="col-4">
                                        <strong>BUDGET</strong> {{ job.budget }}
                                    </div>
                                </div>
                            </div>

                            <div class="row"><p></p></div>

                            <div class="row">
                                <p class="col-12"><strong>Source text:</strong> {{ job.source_text }}</p>
                            </div>

                            <div class="row justify-content-around">
                                {% if not job.user == user and user.is_translator %}   
                                
                                    <p class="btn btn-primary"><a href="{% url 'app:job_bidding' job.id %}" class="text-white">Bid on Job</a></p>
                                
                                {% endif %}     

                                {% if not job.user == user %}
                                    <p class="btn btn-primary"><a href="{% url 'accounts:send_message' user.id job.user.id %}" class="text-white">Message User</a></p>
                                {% endif %}
                            </div> 
                        </div> 
                    </div>
                    <br>
                {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

translate_o_rama/app/templates/app/post_job.html
{% extends 'app/base.html' %}
{% block content %}
{% load widget_tweaks %}

<h1>Post a job</h1>

<form method="post">
    {% csrf_token %}

    {% for hidden in form.hidden_fields %}
      {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field|add_class:'form-control' }}
        {% for error in field.errors %}
          <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}
      </div>
    {% endfor %}

    {% if form.non_field_errors %}
      <div class="alert alert-danger">
        {{ form.non_field_errors }}
      </div>
    {% endif %}

    <div class="form-group">
      <button type="submit" class="btn btn-primary">
        <span class="glyphicon glyphicon-ok"></span> Post job
      </button>
    </div>

</form>

{% endblock %}

translate_o_rama/app/templates/app/rate_job.html
{% extends 'app/base.html' %}
{% block content %}
{% load widget_tweaks %}

<div class="card mb-3 border-primary p-3">
  <h2 class="text-center bg-primary text-white rounded pt-2 pb-2 mb-4">Rate job</h2>

<div class="container overflow-hidden">
  <div class="row">

      <div class="col-6">
          <div class="card border-primary mb-3">
              <div class="card-header text-primary">Job info - {{ job.title }}</div>
              <div class="card-body text-primary">
                  <h2 class="card-title">From {{ job.source_language }} to {{ job.target_language }}</h2>
                  <h5 class="card-title">Description: {{ job.description }}</h5>
                  <p>Source text: {{ job.source_text }}</p>
                  <p>Translated text: {{ job.translated_text }}</p>
              </div>
          </div>
          
      </div>

      <div class="col-6">

      <form method="post">
          {% csrf_token %}

          {% for hidden in form.hidden_fields %}
            {{ hidden }}
          {% endfor %}

          {% for field in form.visible_fields %}
            <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {{ field|add_class:'form-control' }}
              {% for error in field.errors %}
                <div class="alert alert-danger">{{ error }}</div>
              {% endfor %}
            </div>
          {% endfor %}

          {% if form.non_field_errors %}
            <div class="alert alert-danger">
              {{ form.non_field_errors }}
            </div>
          {% endif %}

          <div class="form-group">
            <button type="submit" class="btn btn-primary">
              <span class="glyphicon glyphicon-ok"></span> Rate job
            </button>
          </div>
      </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}